# Generated by Django 4.2.11 on 2024-03-30 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('honorarios_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PDF',
            new_name='PDF_model',
        ),
    ]
