# Generated by Django 5.0.4 on 2024-04-20 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honorarios_api', '0002_rename_pdf_pdf_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='File_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binary', models.BinaryField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('med', models.CharField(default='', max_length=100)),
                ('clinic', models.CharField(default='', max_length=100)),
                ('file_type', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='PDF_model',
        ),
    ]
