# Generated by Django 5.0.4 on 2024-04-20 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honorarios_api', '0004_alter_file_model_binary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_model',
            name='binary',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
